apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-service-sandbox
  name: api-service-sandbox
  namespace: production-tracker-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service-sandbox
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-service-sandbox
    spec:
      containers:
      - image: rwilsonebi/production-tracker:latest
        imagePullPolicy: Always
        name: api-service-sandbox
        env:
        - name: TRACKER_POSTGRESQL_DB_HOST
          value: production-tracker-database
        - name: TRACKER_POSTGRESQL_DB_PORT
          value: "5432"
        - name: REDEPLOY_KEY
          value: "STRING_REPLACED_DURING_REDEPLOY"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
